
package frames;

import guifortest.Informer;
import guifortest.JSONWorker;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author clear_atom
 */
public class MainFrame extends javax.swing.JFrame {

    String selectedFile;
    JSONWorker jsWorker;
    Informer informer;
    
    public MainFrame(String file, Informer informer) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.selectedFile = file;
        this.jsWorker = new JSONWorker(this.selectedFile);
        this.informer = informer;
    }

    @Override
    protected void processWindowEvent(WindowEvent e){
        if (e.getID() == WindowEvent.WINDOW_CLOSING){
            if (informer == null)
                System.exit(0);
            boolean exit = informer.checkIfNoEmptyFields();
            if (exit)
                System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAddGreet = new javax.swing.JButton();
        jButtonAddQuestions = new javax.swing.JButton();
        jButtonAddReactions = new javax.swing.JButton();
        jButtonAddCommands = new javax.swing.JButton();
        jButtonAddRule3 = new javax.swing.JButton();
        jButtonFinalSettings = new javax.swing.JButton();
        jButtonAddRules = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonAddGroups = new javax.swing.JButton();
        jButtonAddSeveralPlayers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 241, 254));

        jButtonAddGreet.setBackground(new java.awt.Color(197, 239, 247));
        jButtonAddGreet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAddGreet.setText("Add new greeting");
        jButtonAddGreet.setToolTipText("");
        jButtonAddGreet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddGreet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddGreetMouseClicked(evt);
            }
        });
        jButtonAddGreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddGreetActionPerformed(evt);
            }
        });

        jButtonAddQuestions.setBackground(new java.awt.Color(197, 239, 247));
        jButtonAddQuestions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAddQuestions.setText("Add questions");
        jButtonAddQuestions.setToolTipText("");
        jButtonAddQuestions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddQuestions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddQuestionsMouseClicked(evt);
            }
        });
        jButtonAddQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddQuestionsActionPerformed(evt);
            }
        });

        jButtonAddReactions.setBackground(new java.awt.Color(197, 239, 247));
        jButtonAddReactions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAddReactions.setText("Add reactions");
        jButtonAddReactions.setToolTipText("");
        jButtonAddReactions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddReactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddReactionsMouseClicked(evt);
            }
        });
        jButtonAddReactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddReactionsActionPerformed(evt);
            }
        });

        jButtonAddCommands.setBackground(new java.awt.Color(197, 239, 247));
        jButtonAddCommands.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAddCommands.setText("Add commands");
        jButtonAddCommands.setToolTipText("");
        jButtonAddCommands.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddCommands.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddCommandsMouseClicked(evt);
            }
        });
        jButtonAddCommands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCommandsActionPerformed(evt);
            }
        });

        jButtonAddRule3.setBackground(new java.awt.Color(197, 239, 247));
        jButtonAddRule3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAddRule3.setText("Create evaluation");
        jButtonAddRule3.setToolTipText("");
        jButtonAddRule3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddRule3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddRule3MouseClicked(evt);
            }
        });
        jButtonAddRule3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRule3ActionPerformed(evt);
            }
        });

        jButtonFinalSettings.setBackground(new java.awt.Color(197, 239, 247));
        jButtonFinalSettings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFinalSettings.setText("Final settings");
        jButtonFinalSettings.setToolTipText("");
        jButtonFinalSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFinalSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFinalSettingsMouseClicked(evt);
            }
        });
        jButtonFinalSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalSettingsActionPerformed(evt);
            }
        });

        jButtonAddRules.setBackground(new java.awt.Color(197, 239, 247));
        jButtonAddRules.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAddRules.setText("Add new rule");
        jButtonAddRules.setToolTipText("");
        jButtonAddRules.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddRules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddRulesMouseClicked(evt);
            }
        });
        jButtonAddRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRulesActionPerformed(evt);
            }
        });

        jButtonBack.setBackground(new java.awt.Color(241, 130, 141));
        jButtonBack.setText("Back");
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackMouseClicked(evt);
            }
        });

        jButtonAddGroups.setBackground(new java.awt.Color(197, 239, 247));
        jButtonAddGroups.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAddGroups.setText("Add groups");
        jButtonAddGroups.setToolTipText("");
        jButtonAddGroups.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddGroups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddGroupsMouseClicked(evt);
            }
        });
        jButtonAddGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddGroupsActionPerformed(evt);
            }
        });

        jButtonAddSeveralPlayers.setBackground(new java.awt.Color(197, 239, 247));
        jButtonAddSeveralPlayers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAddSeveralPlayers.setText("Multiple players");
        jButtonAddSeveralPlayers.setToolTipText("");
        jButtonAddSeveralPlayers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddSeveralPlayers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddSeveralPlayersMouseClicked(evt);
            }
        });
        jButtonAddSeveralPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSeveralPlayersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAddRules, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                .addComponent(jButtonAddCommands, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAddQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAddRule3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAddGreet, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAddReactions, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAddGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAddSeveralPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jButtonFinalSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddGreet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddReactions, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddCommands, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddRules, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddRule3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddSeveralPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButtonFinalSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButtonBack)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddGreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddGreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddGreetActionPerformed

    private void jButtonAddGreetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddGreetMouseClicked
        greetingFrame grFrame;
        try {
            grFrame = new greetingFrame(selectedFile, jsWorker, informer);
            grFrame.setVisible(true);
            grFrame.pack();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddGreetMouseClicked

    private void jButtonAddQuestionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddQuestionsMouseClicked
        questionFrame qFrame;
        try {
            qFrame = new questionFrame(selectedFile, jsWorker, informer);
            qFrame.setLocationRelativeTo(this);
            qFrame.setVisible(true);
            qFrame.pack();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddQuestionsMouseClicked

    private void jButtonAddQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddQuestionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddQuestionsActionPerformed

    private void jButtonAddReactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddReactionsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddReactionsMouseClicked

    private void jButtonAddReactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddReactionsActionPerformed
        reactionsFrame rFrame;
        try {
            rFrame = new reactionsFrame(selectedFile, jsWorker, informer);
            rFrame.setVisible(true);
            rFrame.pack();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddReactionsActionPerformed

    private void jButtonAddCommandsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddCommandsMouseClicked
        commandsFrame cFrame;
        try {
            cFrame = new commandsFrame(selectedFile, jsWorker, informer);
            cFrame.setVisible(true);
            cFrame.pack();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddCommandsMouseClicked

    private void jButtonAddCommandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCommandsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddCommandsActionPerformed

    private void jButtonAddRule3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddRule3MouseClicked
        evaluationFrame eFrame;
        try {
            eFrame = new evaluationFrame(selectedFile, informer);
            eFrame.setLocationRelativeTo(this);
            eFrame.setVisible(true);
            eFrame.pack();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddRule3MouseClicked

    private void jButtonAddRule3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRule3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddRule3ActionPerformed

    private void jButtonFinalSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFinalSettingsMouseClicked
        settingsFrame sFrame;
        try {
            sFrame = new settingsFrame(selectedFile, informer);
            sFrame.setLocationRelativeTo(this);
            sFrame.setVisible(true);
            sFrame.pack();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFinalSettingsMouseClicked

    private void jButtonFinalSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFinalSettingsActionPerformed

    private void jButtonAddRulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddRulesMouseClicked
        rulesFrame rFrame;
        try {
            rFrame = new rulesFrame(selectedFile, jsWorker, informer);
            rFrame.setLocationRelativeTo(this);
            rFrame.setVisible(true);
            rFrame.pack();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddRulesMouseClicked

    private void jButtonAddRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRulesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddRulesActionPerformed

    private void jButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackMouseClicked
        openFrame oFrame = new openFrame(informer);
        oFrame.setVisible(true);
        oFrame.pack();
        this.dispose();
    }//GEN-LAST:event_jButtonBackMouseClicked

    private void jButtonAddGroupsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddGroupsMouseClicked
        groupsFrame gFrame;
        try {
            gFrame = new groupsFrame(selectedFile, jsWorker, informer);
            gFrame.setLocationRelativeTo(this);
            gFrame.setVisible(true);
            gFrame.pack();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddGroupsMouseClicked

    private void jButtonAddGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddGroupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddGroupsActionPerformed

    private void jButtonAddSeveralPlayersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddSeveralPlayersMouseClicked
        multiPlayersFrame pFrame;
        try {
            pFrame = new multiPlayersFrame(selectedFile, jsWorker, informer);
            pFrame.setLocationRelativeTo(this);
            pFrame.setVisible(true);
            pFrame.pack();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddSeveralPlayersMouseClicked

    private void jButtonAddSeveralPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSeveralPlayersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddSeveralPlayersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCommands;
    private javax.swing.JButton jButtonAddGreet;
    private javax.swing.JButton jButtonAddGroups;
    private javax.swing.JButton jButtonAddQuestions;
    private javax.swing.JButton jButtonAddReactions;
    private javax.swing.JButton jButtonAddRule3;
    private javax.swing.JButton jButtonAddRules;
    private javax.swing.JButton jButtonAddSeveralPlayers;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonFinalSettings;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
