/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import guifortest.Informer;
import guifortest.JSONWorker;
import javax.swing.DefaultListModel;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author clear_atom
 */
public class multiPlayersFrame extends javax.swing.JFrame {

    String selectedFile;
    JSONWorker jsWorker;
    DefaultListModel<String> modelWin = new DefaultListModel<>();
    DefaultListModel<String> modelDraw = new DefaultListModel<>();
    Informer informer;
    
    public multiPlayersFrame(String file, JSONWorker jsWorker, Informer informer) throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        this.informer = informer;
        this.jsWorker = jsWorker;
        this.selectedFile = file;
        this.listWinReact.setModel(modelWin);
        this.listDrawReactions.setModel(modelDraw);
        jsWorker.fillList("reactionsForMultiPlayers", "win", modelWin);
        jsWorker.fillList("reactionsForMultiPlayers", "draw", modelDraw);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonOKWin = new javax.swing.JButton();
        jTextWinReact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDrawReact = new javax.swing.JTextField();
        jButtonOkDraw = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listWinReact = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listDrawReactions = new javax.swing.JList<>();
        jButtonDelWin = new javax.swing.JButton();
        jButtonDraw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 241, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Reactions for win/draw when multiple players");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 500, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Win reactions");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 162, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Draw reactions");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 162, -1));

        jButtonOKWin.setBackground(new java.awt.Color(123, 239, 178));
        jButtonOKWin.setText("OK");
        jButtonOKWin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOKWin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOKWinMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonOKWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 70, 30));

        jTextWinReact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextWinReactActionPerformed(evt);
            }
        });
        jPanel1.add(jTextWinReact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 670, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Add win reaction");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 110, -1));
        jPanel1.add(jTextFieldDrawReact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 670, 30));

        jButtonOkDraw.setBackground(new java.awt.Color(123, 239, 178));
        jButtonOkDraw.setText("OK");
        jButtonOkDraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOkDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOkDrawMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonOkDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 70, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Add draw reaction");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 130, -1));

        jButtonBack.setBackground(new java.awt.Color(241, 130, 141));
        jButtonBack.setText("Back");
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jScrollPane2.setViewportView(listWinReact);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 50, 670, 100));

        jScrollPane3.setViewportView(listDrawReactions);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 670, 110));

        jButtonDelWin.setBackground(new java.awt.Color(241, 231, 254));
        jButtonDelWin.setText("Delete");
        jButtonDelWin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDelWinMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonDelWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        jButtonDraw.setBackground(new java.awt.Color(241, 231, 254));
        jButtonDraw.setText("Delete");
        jButtonDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDrawMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKWinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOKWinMouseClicked
        jsWorker.addText(modelWin, jTextWinReact, "reactionsForMultiPlayers", "win");
    }//GEN-LAST:event_jButtonOKWinMouseClicked

    private void jTextWinReactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextWinReactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextWinReactActionPerformed

    private void jButtonOkDrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOkDrawMouseClicked
        jsWorker.addText(modelDraw, jTextFieldDrawReact, "reactionsForMultiPlayers", "draw");
    }//GEN-LAST:event_jButtonOkDrawMouseClicked

    private void jButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackMouseClicked
        MainFrame mFrame = new MainFrame(selectedFile, informer);
        mFrame.setVisible(true);
        mFrame.pack();
        this.dispose();
    }//GEN-LAST:event_jButtonBackMouseClicked

    private void jButtonDelWinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDelWinMouseClicked
        try {
            jsWorker.deleteFromList(modelWin, this.listWinReact, "reactionsForMultiPlayers", "win");
        } catch (Exception ex) {
            Logger.getLogger(greetingFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDelWinMouseClicked

    private void jButtonDrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDrawMouseClicked
        try {
            jsWorker.deleteFromList(modelDraw, this.listDrawReactions, "reactionsForMultiPlayers", "draw");
        } catch (Exception ex) {
            Logger.getLogger(greetingFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDrawMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelWin;
    private javax.swing.JButton jButtonDraw;
    private javax.swing.JButton jButtonOKWin;
    private javax.swing.JButton jButtonOkDraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldDrawReact;
    private javax.swing.JTextField jTextWinReact;
    private javax.swing.JList<String> listDrawReactions;
    private javax.swing.JList<String> listWinReact;
    // End of variables declaration//GEN-END:variables
}
