
package frames;
import guifortest.Informer;
import java.awt.event.WindowEvent;
import javax.swing.JFileChooser;
import java.io.File;  
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author clear_atom
 */
public class openFrame extends javax.swing.JFrame {

    Informer informer;
    
    public openFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public openFrame(Informer informer){
        this.informer = informer;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBChooseFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBCreateFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 241, 254));

        jBChooseFile.setBackground(new java.awt.Color(197, 239, 247));
        jBChooseFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBChooseFile.setText("Choose File");
        jBChooseFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBChooseFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBChooseFileMouseClicked(evt);
            }
        });
        jBChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChooseFileActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Welcome to an application ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("which allows you to create ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("simple tests for Humanoid robot Pepper");

        jBCreateFile.setBackground(new java.awt.Color(197, 239, 247));
        jBCreateFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCreateFile.setText("Create new File");
        jBCreateFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCreateFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCreateFileMouseClicked(evt);
            }
        });
        jBCreateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreateFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jBCreateFile, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCreateFile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void processWindowEvent(WindowEvent e){
        if (e.getID() == WindowEvent.WINDOW_CLOSING){
            if (informer == null)
                System.exit(0);
            boolean exit = informer.checkIfNoEmptyFields();
            if (exit)
                System.exit(0);
        }
   }
    
    private void jBChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChooseFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            
            if (selectedFile != null)
                try {
                    startNewApp(selectedFile.getAbsolutePath(), false);
            } catch (Exception ex) {
                Logger.getLogger(openFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
    }//GEN-LAST:event_jBChooseFileActionPerformed

    private void jBCreateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreateFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCreateFileActionPerformed

    private void jBChooseFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBChooseFileMouseClicked
        
    }//GEN-LAST:event_jBChooseFileMouseClicked

    private void setAll(String selectedFile) throws Exception{
        this.informer = new Informer (selectedFile);
        informer.setSimpleKeys(new String [] {"greetings", "rules", "questions"});
        informer.setSimpleValues(new String [] {"evaluateImmediately", "tellPoints", "numOfQuestions"});
        informer.setTypesOfSimpleValues(new String [] {"bool", "bool", "int"});
        informer.setDoubleKeys(new String [][] {{"reactions", "positive", "negative"}, {"commands", "stop", "volume_up", "volume_down"}, {"points"}});
        informer.checkAll();
    }
        
    private void startNewApp(String selectedFile, boolean newF) throws Exception{
        if (newF)
            setAll(selectedFile);
        MainFrame mFrame = new MainFrame(selectedFile, informer);
        mFrame.setVisible(true);
        mFrame.pack();
        this.dispose();
    }
    private void jBCreateFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCreateFileMouseClicked
        String fileName = JOptionPane.showInputDialog("Enter file name") + ".json";
        File selectedFile = null;
        int res = JOptionPane.showConfirmDialog(rootPane, "Create file " + fileName);
        if (res == 0){
            try {
          selectedFile = new File(fileName);
          if (selectedFile.createNewFile()) {
              JOptionPane.showMessageDialog(rootPane, "File created: " + selectedFile.getName());
          } else {
              JOptionPane.showMessageDialog(rootPane, "File already exists.");
          }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "An error occurred.");
            }
        }
        
        if (selectedFile != null){
            try {
                startNewApp(selectedFile.getAbsolutePath(), true);
            } catch (Exception ex) {
                Logger.getLogger(openFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBCreateFileMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBChooseFile;
    private javax.swing.JButton jBCreateFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
