
package frames;

import guifortest.Informer;
import guifortest.JSONWorker;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author clear_atom
 */
public class reactionsFrame extends javax.swing.JFrame {

    String selectedFile;
    JSONWorker jsWorker;
    DefaultListModel<String> modelPos = new DefaultListModel<>();
    DefaultListModel<String> modelNeg = new DefaultListModel<>();
    Informer informer;
    
    public reactionsFrame(String file, JSONWorker jsWorker, Informer informer) throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jsWorker = jsWorker;
        this.selectedFile = file;
        this.listPosReact.setModel(modelPos);
        this.listNegReact.setModel(modelNeg);
        this.informer = informer;
        jsWorker.fillList("reactions", "positive", modelPos);
        jsWorker.fillList("reactions", "negative", modelNeg);
    }

    @Override
    protected void processWindowEvent(WindowEvent e){
        if (e.getID() == WindowEvent.WINDOW_CLOSING){
            if (informer == null)
                System.exit(0);
            boolean exit = informer.checkIfNoEmptyFields();
            if (exit)
                System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonOKPos = new javax.swing.JButton();
        jTextFieldPosReact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNegReac = new javax.swing.JTextField();
        jButtonOKNeg = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNegReact = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPosReact = new javax.swing.JList<>();
        jButtonDeletePos = new javax.swing.JButton();
        jButtonDeleteNeg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 241, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Reactions for answers");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 293, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Positive");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 162, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Negative");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 162, -1));

        jButtonOKPos.setBackground(new java.awt.Color(123, 239, 178));
        jButtonOKPos.setText("OK");
        jButtonOKPos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOKPos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOKPosMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonOKPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 70, 30));

        jTextFieldPosReact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPosReactActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPosReact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 670, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Add positive reaction");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 110, -1));
        jPanel1.add(jTextFieldNegReac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 670, 30));

        jButtonOKNeg.setBackground(new java.awt.Color(123, 239, 178));
        jButtonOKNeg.setText("OK");
        jButtonOKNeg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOKNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOKNegMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonOKNeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 70, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Add negative reaction");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 130, -1));

        jButtonBack.setBackground(new java.awt.Color(241, 130, 141));
        jButtonBack.setText("Back");
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackMouseClicked(evt);
            }
        });
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jScrollPane1.setViewportView(listNegReact);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 670, 110));

        jScrollPane2.setViewportView(listPosReact);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 60, 670, 110));

        jButtonDeletePos.setBackground(new java.awt.Color(241, 231, 254));
        jButtonDeletePos.setText("Delete");
        jButtonDeletePos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeletePos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeletePosMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonDeletePos, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        jButtonDeleteNeg.setBackground(new java.awt.Color(241, 231, 254));
        jButtonDeleteNeg.setText("Delete");
        jButtonDeleteNeg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteNegMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonDeleteNeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKPosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOKPosMouseClicked
        jsWorker.addText(modelPos, jTextFieldPosReact, "reactions", "positive");
    }//GEN-LAST:event_jButtonOKPosMouseClicked

    private void jButtonOKNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOKNegMouseClicked
        jsWorker.addText(modelNeg, jTextFieldNegReac, "reactions", "negative");
    }//GEN-LAST:event_jButtonOKNegMouseClicked

    private void jButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackMouseClicked
        MainFrame mFrame = new MainFrame(selectedFile, informer);
        mFrame.setVisible(true);
        mFrame.pack();
        this.dispose();
    }//GEN-LAST:event_jButtonBackMouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldPosReactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPosReactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPosReactActionPerformed

    private void jButtonDeletePosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeletePosMouseClicked
        try {
            jsWorker.deleteFromList(this.modelPos, this.listPosReact, "reactions", "positive");
        } catch (Exception ex) {
            Logger.getLogger(greetingFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDeletePosMouseClicked

    private void jButtonDeleteNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteNegMouseClicked
        try {
            jsWorker.deleteFromList(this.modelNeg, this.listNegReact, "reactions", "negative");
        } catch (Exception ex) {
            Logger.getLogger(greetingFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDeleteNegMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDeleteNeg;
    private javax.swing.JButton jButtonDeletePos;
    private javax.swing.JButton jButtonOKNeg;
    private javax.swing.JButton jButtonOKPos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldNegReac;
    private javax.swing.JTextField jTextFieldPosReact;
    private javax.swing.JList<String> listNegReact;
    private javax.swing.JList<String> listPosReact;
    // End of variables declaration//GEN-END:variables
}
